#include "debug.h"
#include <stdio.h>

typedef struct _opc {
    char ins;
    char cmd[64];
    char addrmd[64];
    char flags[64];
} opc_t;

opc_t table[] = {
    { .ins = 0x00, .cmd = "BRK", .addrmd = "Implied", .flags = "- - - - - - - " },
    { .ins = 0x01, .cmd = "ORA ($NN,X)", .addrmd = "Indexed Indirect", .flags = "- Z- - - - N" },
    { .ins = 0x02, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x03, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x04, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x05, .cmd = "ORA $NN", .addrmd = "Zero Page", .flags = "- Z- - - - N" },
    { .ins = 0x06, .cmd = "ASL $NN", .addrmd = "Zero Page", .flags = "CZ- - - - N" },
    { .ins = 0x07, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x08, .cmd = "PHP", .addrmd = "Implied", .flags = "- - - - - - - " },
    { .ins = 0x09, .cmd = "ORA #$NN", .addrmd = "Immediate", .flags = "- Z- - - - N" },
    { .ins = 0x0a, .cmd = "ASL A", .addrmd = "Accumulator", .flags = "CZ- - - - N" },
    { .ins = 0x0b, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x0c, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x0d, .cmd = "ORA $NNNN", .addrmd = "Absolute", .flags = "- Z- - - - N" },
    { .ins = 0x0e, .cmd = "ASL $NNNN", .addrmd = "Absolute", .flags = "CZ- - - - N" },
    { .ins = 0x0f, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x10, .cmd = "BPL $NN", .addrmd = "Relative", .flags = "- - - - - - - " },
    { .ins = 0x11, .cmd = "ORA ($NN),Y", .addrmd = "Indirect Indexed", .flags = "- Z- - - - N" },
    { .ins = 0x12, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x13, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x14, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x15, .cmd = "ORA $NN,X", .addrmd = "Zero Page,X", .flags = "- Z- - - - N" },
    { .ins = 0x16, .cmd = "ASL $NN,X", .addrmd = "Zero Page,X", .flags = "CZ- - - - N" },
    { .ins = 0x17, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x18, .cmd = "CLC", .addrmd = "Implied", .flags = "C- - - - - - " },
    { .ins = 0x19, .cmd = "ORA $NNNN,Y", .addrmd = "Absolute,Y", .flags = "- Z- - - - N" },
    { .ins = 0x1a, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x1b, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x1c, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x1d, .cmd = "ORA $NNNN,X", .addrmd = "Absolute,X", .flags = "- Z- - - - N" },
    { .ins = 0x1e, .cmd = "ASL $NNNN,X", .addrmd = "Absolute,X", .flags = "CZ- - - - N" },
    { .ins = 0x1f, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x20, .cmd = "JSR $NNNN", .addrmd = "Absolute", .flags = "- - - - - - - " },
    { .ins = 0x21, .cmd = "AND ($NN,X)", .addrmd = "Indexed Indirect", .flags = "- Z- - - - N" },
    { .ins = 0x22, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x23, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x24, .cmd = "BIT $NN", .addrmd = "Zero Page", .flags = "- Z- - - VN" },
    { .ins = 0x25, .cmd = "AND $NN", .addrmd = "Zero Page", .flags = "- Z- - - - N" },
    { .ins = 0x26, .cmd = "ROL $NN", .addrmd = "Zero Page", .flags = "CZ- - - - N" },
    { .ins = 0x27, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x28, .cmd = "PLP", .addrmd = "Implied", .flags = "CZIDBVN" },
    { .ins = 0x29, .cmd = "AND #$NN", .addrmd = "Immediate", .flags = "- Z- - - - N" },
    { .ins = 0x2a, .cmd = "ROL A", .addrmd = "Accumulator", .flags = "CZ- - - - N" },
    { .ins = 0x2b, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x2c, .cmd = "BIT $NNNN", .addrmd = "Absolute", .flags = "- Z- - - VN" },
    { .ins = 0x2d, .cmd = "AND $NNNN", .addrmd = "Absolute", .flags = "- Z- - - - N" },
    { .ins = 0x2e, .cmd = "ROL $NNNN", .addrmd = "Absolute", .flags = "CZ- - - - N" },
    { .ins = 0x2f, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x30, .cmd = "BMI $NN", .addrmd = "Relative", .flags = "- - - - - - - " },
    { .ins = 0x31, .cmd = "AND ($NN),Y", .addrmd = "Indirect Indexed", .flags = "- Z- - - - N" },
    { .ins = 0x32, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x33, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x34, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x35, .cmd = "AND $NN,X", .addrmd = "Zero Page,X", .flags = "- Z- - - - N" },
    { .ins = 0x36, .cmd = "ROL $NN,X", .addrmd = "Zero Page,X", .flags = "CZ- - - - N" },
    { .ins = 0x37, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x38, .cmd = "SEC", .addrmd = "Implied", .flags = "C- - - - - - " },
    { .ins = 0x39, .cmd = "AND $NNNN,Y", .addrmd = "Absolute,Y", .flags = "- Z- - - - N" },
    { .ins = 0x3a, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x3b, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x3c, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x3d, .cmd = "AND $NNNN,X", .addrmd = "Absolute,X", .flags = "- Z- - - - N" },
    { .ins = 0x3e, .cmd = "ROL $NNNN,X", .addrmd = "Absolute,X", .flags = "CZ- - - - N" },
    { .ins = 0x3f, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x40, .cmd = "RTI", .addrmd = "Implied", .flags = "- - - - - - - " },
    { .ins = 0x41, .cmd = "EOR ($NN,X)", .addrmd = "Indexed Indirect", .flags = "- Z- - - - N" },
    { .ins = 0x42, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x43, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x44, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x45, .cmd = "EOR $NN", .addrmd = "Zero Page", .flags = "- Z- - - - N" },
    { .ins = 0x46, .cmd = "LSR $NN", .addrmd = "Zero Page", .flags = "CZ- - - - N" },
    { .ins = 0x47, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x48, .cmd = "PHA", .addrmd = "Implied", .flags = "- - - - - - - " },
    { .ins = 0x49, .cmd = "EOR #$NN", .addrmd = "Immediate", .flags = "- Z- - - - N" },
    { .ins = 0x4a, .cmd = "LSR A", .addrmd = "Accumulator", .flags = "CZ- - - - N" },
    { .ins = 0x4b, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x4c, .cmd = "JMP $NNNN", .addrmd = "Absolute", .flags = "- - - - - - - " },
    { .ins = 0x4d, .cmd = "EOR $NNNN", .addrmd = "Absolute", .flags = "- Z- - - - N" },
    { .ins = 0x4e, .cmd = "LSR $NNNN", .addrmd = "Absolute", .flags = "CZ- - - - N" },
    { .ins = 0x4f, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x50, .cmd = "BVC $NN", .addrmd = "Relative", .flags = "- - - - - - - " },
    { .ins = 0x51, .cmd = "EOR ($NN),Y", .addrmd = "Indirect Indexed", .flags = "- Z- - - - N" },
    { .ins = 0x52, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x53, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x54, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x55, .cmd = "EOR $NN,X", .addrmd = "Zero Page,X", .flags = "- Z- - - - N" },
    { .ins = 0x56, .cmd = "LSR $NN,X", .addrmd = "Zero Page,X", .flags = "CZ- - - - N" },
    { .ins = 0x57, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x58, .cmd = "CLI", .addrmd = "Implied", .flags = "- - I- - - - " },
    { .ins = 0x59, .cmd = "EOR $NNNN,Y", .addrmd = "Absolute,Y", .flags = "- Z- - - - N" },
    { .ins = 0x5a, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x5b, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x5c, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x5d, .cmd = "EOR $NNNN,X", .addrmd = "Absolute,X", .flags = "- Z- - - - N" },
    { .ins = 0x5e, .cmd = "LSR $NNNN,X", .addrmd = "Absolute,X", .flags = "CZ- - - - N" },
    { .ins = 0x5f, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x60, .cmd = "RTS", .addrmd = "Implied", .flags = "- - - - - - - " },
    { .ins = 0x61, .cmd = "ADC ($NN,X)", .addrmd = "Indexed Indirect", .flags = "CZ- - - VN" },
    { .ins = 0x62, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x63, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x64, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x65, .cmd = "ADC $NN", .addrmd = "Zero Page", .flags = "CZ- - - VN" },
    { .ins = 0x66, .cmd = "ROR $NN", .addrmd = "Zero Page", .flags = "CZ- - - - N" },
    { .ins = 0x67, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x68, .cmd = "PLA", .addrmd = "Implied", .flags = "- Z- - - - N" },
    { .ins = 0x69, .cmd = "ADC #$NN", .addrmd = "Immediate", .flags = "CZ- - - VN" },
    { .ins = 0x6a, .cmd = "ROR A", .addrmd = "Accumulator", .flags = "CZ- - - - N" },
    { .ins = 0x6b, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x6c, .cmd = "JMP $NN", .addrmd = "Indirect", .flags = "- - - - - - - " },
    { .ins = 0x6d, .cmd = "ADC $NNNN", .addrmd = "Absolute", .flags = "CZ- - - VN" },
    { .ins = 0x6e, .cmd = "ROR $NNNN,X", .addrmd = "Absolute,X", .flags = "CZ- - - - N" },
    { .ins = 0x6f, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x70, .cmd = "BVS $NN", .addrmd = "Relative", .flags = "- - - - - - - " },
    { .ins = 0x71, .cmd = "ADC ($NN),Y", .addrmd = "Indirect Indexed", .flags = "CZ- - - VN" },
    { .ins = 0x72, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x73, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x74, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x75, .cmd = "ADC $NN,X", .addrmd = "Zero Page,X", .flags = "CZ- - - VN" },
    { .ins = 0x76, .cmd = "ROR $NN,X", .addrmd = "Zero Page,X", .flags = "CZ- - - - N" },
    { .ins = 0x77, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x78, .cmd = "SEI", .addrmd = "Implied", .flags = "- - I- - - - " },
    { .ins = 0x79, .cmd = "ADC $NNNN,Y", .addrmd = "Absolute,Y", .flags = "CZ- - - VN" },
    { .ins = 0x7a, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x7b, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x7c, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x7d, .cmd = "ADC $NNNN,X", .addrmd = "Absolute,X", .flags = "CZ- - - VN" },
    { .ins = 0x7e, .cmd = "ROR $NNNN", .addrmd = "Absolute", .flags = "CZ- - - - N" },
    { .ins = 0x7f, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x80, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x81, .cmd = "STA ($NN,X)", .addrmd = "Indexed Indirect", .flags = "- - - - - - - " },
    { .ins = 0x82, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x83, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x84, .cmd = "STY $NN", .addrmd = "Zero Page", .flags = "- - - - - - - " },
    { .ins = 0x85, .cmd = "STA $NN", .addrmd = "Zero Page", .flags = "- - - - - - - " },
    { .ins = 0x86, .cmd = "STX $NN", .addrmd = "Zero Page", .flags = "- - - - - - - " },
    { .ins = 0x87, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x88, .cmd = "DEY", .addrmd = "Implied", .flags = "- Z- - - - N" },
    { .ins = 0x89, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x8a, .cmd = "TXA", .addrmd = "Implied", .flags = "- Z- - - - N" },
    { .ins = 0x8b, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x8c, .cmd = "STY $NNNN", .addrmd = "Absolute", .flags = "- - - - - - - " },
    { .ins = 0x8d, .cmd = "STA $NNNN", .addrmd = "Absolute", .flags = "- - - - - - - " },
    { .ins = 0x8e, .cmd = "STX $NNNN", .addrmd = "Absolute", .flags = "- - - - - - - " },
    { .ins = 0x8f, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x90, .cmd = "BCC $NN", .addrmd = "Relative", .flags = "- - - - - - - " },
    { .ins = 0x91, .cmd = "STA ($NN),Y", .addrmd = "Indirect Indexed", .flags = "- - - - - - - " },
    { .ins = 0x92, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x93, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x94, .cmd = "STY $NN,X", .addrmd = "Zero Page,X", .flags = "- - - - - - - " },
    { .ins = 0x95, .cmd = "STA $NN,X", .addrmd = "Zero Page,X", .flags = "- - - - - - - " },
    { .ins = 0x96, .cmd = "STX $NN,Y", .addrmd = "Zero Page,Y", .flags = "- - - - - - - " },
    { .ins = 0x97, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x98, .cmd = "TYA", .addrmd = "Implied", .flags = "- Z- - - - N" },
    { .ins = 0x99, .cmd = "STA $NNNN,Y", .addrmd = "Absolute,Y", .flags = "- - - - - - - " },
    { .ins = 0x9a, .cmd = "TXS", .addrmd = "Implied", .flags = "- - - - - - - " },
    { .ins = 0x9b, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x9c, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x9d, .cmd = "STA $NNNN,X", .addrmd = "Absolute,X", .flags = "- - - - - - - " },
    { .ins = 0x9e, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0x9f, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xa0, .cmd = "LDY #$NN", .addrmd = "Immediate", .flags = "- Z- - - - N" },
    { .ins = 0xa1, .cmd = "LDA ($NN,X)", .addrmd = "Indexed Indirect", .flags = "- Z- - - - N" },
    { .ins = 0xa2, .cmd = "LDX #$NN", .addrmd = "Immediate", .flags = "- Z- - - - N" },
    { .ins = 0xa3, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xa4, .cmd = "LDY $NN", .addrmd = "Zero Page", .flags = "- Z- - - - N" },
    { .ins = 0xa5, .cmd = "LDA $NN", .addrmd = "Zero Page", .flags = "- Z- - - - N" },
    { .ins = 0xa6, .cmd = "LDX $NN", .addrmd = "Zero Page", .flags = "- Z- - - - N" },
    { .ins = 0xa7, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xa8, .cmd = "TAY", .addrmd = "Implied", .flags = "- Z- - - - N" },
    { .ins = 0xa9, .cmd = "LDA #$NN", .addrmd = "Immediate", .flags = "- Z- - - - N" },
    { .ins = 0xaa, .cmd = "TAX", .addrmd = "Implied", .flags = "- Z- - - - N" },
    { .ins = 0xab, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xac, .cmd = "LDY $NNNN", .addrmd = "Absolute", .flags = "- Z- - - - N" },
    { .ins = 0xad, .cmd = "LDA $NNNN", .addrmd = "Absolute", .flags = "- Z- - - - N" },
    { .ins = 0xae, .cmd = "LDX $NNNN", .addrmd = "Absolute", .flags = "- Z- - - - N" },
    { .ins = 0xaf, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xb0, .cmd = "BCS $NN", .addrmd = "Relative", .flags = "- - - - - - - " },
    { .ins = 0xb1, .cmd = "LDA ($NN),Y", .addrmd = "Indirect Indexed", .flags = "- Z- - - - N" },
    { .ins = 0xb2, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xb3, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xb4, .cmd = "LDY $NN,X", .addrmd = "Zero Page,X", .flags = "- Z- - - - N" },
    { .ins = 0xb5, .cmd = "LDA $NN,X", .addrmd = "Zero Page,X", .flags = "- Z- - - - N" },
    { .ins = 0xb6, .cmd = "LDX $NN,Y", .addrmd = "Zero Page,Y", .flags = "- Z- - - - N" },
    { .ins = 0xb7, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xb8, .cmd = "CLV", .addrmd = "Implied", .flags = "- - - - - V- " },
    { .ins = 0xb9, .cmd = "LDA $NNNN,Y", .addrmd = "Absolute,Y", .flags = "- Z- - - - N" },
    { .ins = 0xba, .cmd = "TSX", .addrmd = "Implied", .flags = "- Z- - - - N" },
    { .ins = 0xbb, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xbc, .cmd = "LDY $NNNN,X", .addrmd = "Absolute,X", .flags = "- Z- - - - N" },
    { .ins = 0xbd, .cmd = "LDA $NNNN,X", .addrmd = "Absolute,X", .flags = "- Z- - - - N" },
    { .ins = 0xbe, .cmd = "LDX $NNNN,Y", .addrmd = "Absolute,Y", .flags = "- Z- - - - N" },
    { .ins = 0xbf, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xc0, .cmd = "CPY #$NN", .addrmd = "Immediate", .flags = "CZ- - - - N" },
    { .ins = 0xc1, .cmd = "CMP ($NN,X)", .addrmd = "Indexed Indirect", .flags = "CZ- - - - N" },
    { .ins = 0xc2, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xc3, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xc4, .cmd = "CPY $NN", .addrmd = "Zero Page", .flags = "CZ- - - - N" },
    { .ins = 0xc5, .cmd = "CMP $NN", .addrmd = "Zero Page", .flags = "CZ- - - - N" },
    { .ins = 0xc6, .cmd = "DEC $NN", .addrmd = "Zero Page", .flags = "- Z- - - - N" },
    { .ins = 0xc7, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xc8, .cmd = "INY", .addrmd = "Implied", .flags = "- Z- - - - N" },
    { .ins = 0xc9, .cmd = "CMP #$NN", .addrmd = "Immediate", .flags = "CZ- - - - N" },
    { .ins = 0xca, .cmd = "DEX", .addrmd = "Implied", .flags = "- Z- - - - N" },
    { .ins = 0xcb, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xcc, .cmd = "CPY $NNNN", .addrmd = "Absolute", .flags = "CZ- - - - N" },
    { .ins = 0xcd, .cmd = "CMP $NNNN", .addrmd = "Absolute", .flags = "CZ- - - - N" },
    { .ins = 0xce, .cmd = "DEC $NNNN", .addrmd = "Absolute", .flags = "- Z- - - - N" },
    { .ins = 0xcf, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xd0, .cmd = "BNE $NN", .addrmd = "Relative", .flags = "- - - - - - - " },
    { .ins = 0xd1, .cmd = "CMP ($NN),Y", .addrmd = "Indirect Indexed", .flags = "CZ- - - - N" },
    { .ins = 0xd2, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xd3, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xd4, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xd5, .cmd = "CMP $NN,X", .addrmd = "Zero Page,X", .flags = "CZ- - - - N" },
    { .ins = 0xd6, .cmd = "DEC $NN,X", .addrmd = "Zero Page,X", .flags = "- Z- - - - N" },
    { .ins = 0xd7, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xd8, .cmd = "CLD", .addrmd = "Implied", .flags = "- - - D- - - " },
    { .ins = 0xd9, .cmd = "CMP $NNNN,Y", .addrmd = "Absolute,Y", .flags = "CZ- - - - N" },
    { .ins = 0xda, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xdb, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xdc, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xdd, .cmd = "CMP $NNNN,X", .addrmd = "Absolute,X", .flags = "CZ- - - - N" },
    { .ins = 0xde, .cmd = "DEC $NNNN,X", .addrmd = "Absolute,X", .flags = "- Z- - - - N" },
    { .ins = 0xdf, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xe0, .cmd = "CPX #$NN", .addrmd = "Immediate", .flags = "CZ- - - - N" },
    { .ins = 0xe1, .cmd = "SBC ($NN,X)", .addrmd = "Indexed Indirect", .flags = "CZ- - - VN" },
    { .ins = 0xe2, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xe3, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xe4, .cmd = "CPX $NN", .addrmd = "Zero Page", .flags = "CZ- - - - N" },
    { .ins = 0xe5, .cmd = "SBC $NN", .addrmd = "Zero Page", .flags = "CZ- - - VN" },
    { .ins = 0xe6, .cmd = "INC $NN", .addrmd = "Zero Page", .flags = "- Z- - - - N" },
    { .ins = 0xe7, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xe8, .cmd = "INX", .addrmd = "Implied", .flags = "- Z- - - - N" },
    { .ins = 0xe9, .cmd = "SBC #$NN", .addrmd = "Immediate", .flags = "CZ- - - VN" },
    { .ins = 0xea, .cmd = "NOP", .addrmd = "Implied", .flags = "- - - - - - - " },
    { .ins = 0xeb, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xec, .cmd = "CPX $NNNN", .addrmd = "Absolute", .flags = "CZ- - - - N" },
    { .ins = 0xed, .cmd = "SBC $NNNN", .addrmd = "Absolute", .flags = "CZ- - - VN" },
    { .ins = 0xee, .cmd = "INC $NNNN", .addrmd = "Absolute", .flags = "- Z- - - - N" },
    { .ins = 0xef, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xf0, .cmd = "BEQ $NN", .addrmd = "Relative", .flags = "- - - - - - - " },
    { .ins = 0xf1, .cmd = "SBC ($NN),Y", .addrmd = "Indirect Indexed", .flags = "CZ- - - VN" },
    { .ins = 0xf2, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xf3, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xf4, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xf5, .cmd = "SBC $NN,X", .addrmd = "Zero Page,X", .flags = "CZ- - - VN" },
    { .ins = 0xf6, .cmd = "INC $NN,X", .addrmd = "Zero Page,X", .flags = "- Z- - - - N" },
    { .ins = 0xf7, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xf8, .cmd = "SED", .addrmd = "Implied", .flags = "- - - D- - - " },
    { .ins = 0xf9, .cmd = "SBC $NNNN,Y", .addrmd = "Absolute,Y", .flags = "CZ- - - VN" },
    { .ins = 0xfa, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xfb, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xfc, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" },
    { .ins = 0xfd, .cmd = "SBC $NNNN,X", .addrmd = "Absolute,X", .flags = "CZ- - - VN" },
    { .ins = 0xfe, .cmd = "INC $NNNN,X", .addrmd = "Absolute,X", .flags = "- Z- - - - N" },
    { .ins = 0xff, .cmd = "undefined", .addrmd = "undefined", .flags = "undefined" }
};

void print_opc_info(unsigned char opc) {
    printf("%2x, ", opc);
    printf("%s \n", (table[opc]).cmd);
    printf("Addressing: %s\n", (table[opc]).addrmd);
}